runtime: java11
instance_class: F2

# Explicitly set the memory limit and maximum heap size for the Spring Boot app
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"
  CLOUD_SQL_CONNECTION_NAME: "greetings-256809:asia-south1:greetings-db"
  DB_NAME: "users_db"
  DB_USER: "root"
  DB_PASS: "root"
